setwd("C:\\rafamonge\\ExData_Plotting1\\")
source("GetFile.R")
png(filename = "plot3.png")
file <-GetFile()
plot( file$DateTime, file$Sub_metering_1,type="n", ylab="Energy Sub metering", xlab="")
lines(file$DateTime, file$Sub_metering_1, col="black")
lines(file$DateTime, file$Sub_metering_2, col="red")
lines(file$DateTime, file$Sub_metering_3, col="blue")
legend("topright", pch=20,col =c("black", "red", "blue"), legend=c("Sub_metering_1","Sub_metering 2", "Sub_metering_3"))
dev.off()
message("done")
